export const PACKAGE_CATEGORIES = {
    nextjs: {
        dependencies: ['next', 'react', 'react-dom'],
        devDependencies: [
            'typescript',
            '@types/node',
            '@types/react',
            '@types/react-dom',
            '@types/color',
            '@types/lodash.throttle',
            '@types/qrcode',
            '@types/culori',
        ],
    },
    expo: {
        dependencies: ['expo', 'react', 'react-native', 'expo-router', '@expo/vector-icons'],
        devDependencies: ['typescript', '@types/react'],
    },
    tauri: {
        dependencies: ['@tauri-apps/api', '@tauri-apps/plugin-shell', 'react', 'react-dom'],
        devDependencies: [
            'vite',
            '@vitejs/plugin-react',
            'typescript',
            '@types/react',
            '@types/react-dom',
        ],
    },
    database: {
        prisma: ['prisma', '@prisma/client'],
        drizzle: ['drizzle-orm', 'drizzle-kit'],
        turso: ['@libsql/client', '@prisma/adapter-libsql'],
        supabase: ['@supabase/supabase-js'],
    },
    auth: ['better-auth', 'bcryptjs', 'zod', '@types/bcryptjs'],
    storage: {
        'vercel-blob': ['@vercel/blob'],
        'aws-s3': ['@aws-sdk/client-s3'],
        'supabase-storage': ['@supabase/supabase-js'],
    },
    ui: [
        'lucide-react',
        'react-icons',
        '@radix-ui/react-accordion',
        '@radix-ui/react-alert-dialog',
        '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-avatar',
        '@radix-ui/react-checkbox',
        '@radix-ui/react-collapsible',
        '@radix-ui/react-context-menu',
        '@radix-ui/react-dialog',
        '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-hover-card',
        '@radix-ui/react-icons',
        '@radix-ui/react-label',
        '@radix-ui/react-menubar',
        '@radix-ui/react-navigation-menu',
        '@radix-ui/react-popover',
        '@radix-ui/react-progress',
        '@radix-ui/react-radio-group',
        '@radix-ui/react-scroll-area',
        '@radix-ui/react-select',
        '@radix-ui/react-separator',
        '@radix-ui/react-slider',
        '@radix-ui/react-slot',
        '@radix-ui/react-switch',
        '@radix-ui/react-tabs',
        '@radix-ui/react-toast',
        '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group',
        '@radix-ui/react-tooltip',
        '@radix-ui/react-use-controllable-state',
        'class-variance-authority',
        'clsx',
        'tailwind-merge',
        'react-hook-form',
        '@hookform/resolvers',
        'embla-carousel-react',
        'react-day-picker',
        'react-resizable-panels',
        'input-otp',
        'cmdk',
        'sonner',
        'recharts',
        'vaul',
        'motion',
        '@tanstack/react-table',
        '@tiptap/react',
        '@tiptap/starter-kit',
        '@tiptap/pm',
        '@uidotdev/usehooks',
        '@dnd-kit/core',
        '@dnd-kit/sortable',
        '@dnd-kit/utilities',
        '@dnd-kit/modifiers',
        'date-fns',
        'fuse.js',
        'color',
        'culori',
        'react-use-measure',
        'qrcode.react',
        'react-svg-credit-card-payment-icons',
        'shiki',
        '@shikijs/transformers',
        'lowlight',
        '@codesandbox/sandpack-react',
        '@tiptap/extension-code-block-lowlight',
        '@tiptap/extension-list',
        '@tiptap/extension-subscript',
        '@tiptap/extension-superscript',
        '@tiptap/extension-table',
        '@tiptap/extension-text-style',
        '@tiptap/extension-typography',
        '@tiptap/extensions',
        '@tiptap/suggestion',
        '@tiptap/core',
        'react-dropzone',
        'tippy.js',
        'lodash.throttle',
        'react-image-crop',
        'react-medium-image-zoom',
        'tunnel-rat',
        'ts-key-enum',
        'react-fast-marquee',
        'qrcode',
        'media-chrome',
    ],
    styling: ['tailwindcss', '@tailwindcss/typography'],
} as const;
