/**
 * pubspec.yamlファイルを生成するヘルパー関数
 * Flutterプロジェクトの依存関係と設定を定義する
 */

import path from 'node:path';
import fs from 'fs-extra';
import type { ProjectConfig } from '../../../commands/create/types.js';

/**
 * pubspec.yamlファイルを生成する（Flutterプロジェクトの依存関係と設定）
 * @param config プロジェクト設定
 */
export async function generatePubspecYaml(config: ProjectConfig) {
    const pubspec = `name: ${config.projectName.toLowerCase().replace(/-/g, '_')}
description: "A new Flutter project generated by fluorite-flake."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 状態管理
  provider: ^6.1.1

  # ルーティング
  go_router: ^14.6.2

  # UIコンポーネント
  cupertino_icons: ^1.0.8

  # HTTPクライアント
  http: ^1.2.0

  # ローカルストレージ
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # リンター
  flutter_lints: ^4.0.0

  # テストユーティリティ
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
`;

    await fs.writeFile(path.join(config.projectPath, 'pubspec.yaml'), pubspec);
}
