import type { FrameworkConfig, FrameworkType } from './types.js';

export const FRAMEWORK_CONFIGS: Record<FrameworkType, FrameworkConfig> = {
    nextjs: {
        name: 'nextjs',
        displayName: 'Next.js',
        defaultName: 'my-next-app',
        description: 'React framework for production-ready web applications',
        supportedFeatures: {
            database: true,
            auth: true,
            storage: true,
            deployment: true,
            packageManager: true,
        },
        supportedDatabases: ['none', 'turso', 'supabase'],
        supportedOrms: ['prisma', 'drizzle'],
        supportedStorage: ['none', 'vercel-blob', 'cloudflare-r2', 'aws-s3', 'supabase-storage'],
        versions: {
            next: '15.5.4',
            react: '19.0.0',
            'react-dom': '19.0.0',
            typescript: '^5.6.0',
            tailwindcss: '^4',
            '@types/node': '^22.0.0',
            '@types/react': '^19.0.0',
            '@types/react-dom': '^19.0.0',
        },
        requiredDependencies: ['next', 'react', 'react-dom'],
        devDependencies: ['typescript', '@types/node', '@types/react', '@types/react-dom'],
    },
    expo: {
        name: 'expo',
        displayName: 'Expo',
        defaultName: 'my-expo-app',
        description: 'React Native framework for mobile applications',
        supportedFeatures: {
            database: true,
            auth: true,
            storage: true,
            deployment: false,
            packageManager: true,
        },
        supportedDatabases: ['none', 'turso', 'supabase'],
        supportedOrms: ['prisma', 'drizzle'],
        supportedStorage: ['none', 'cloudflare-r2', 'aws-s3', 'supabase-storage'],
        versions: {
            expo: '~52.0.0',
            react: '18.3.1',
            'react-native': '0.76.5',
            typescript: '^5.3.0',
            '@types/react': '~18.3.0',
            '@expo/vector-icons': '^14.0.0',
            'expo-router': '~4.0.0',
        },
        requiredDependencies: [
            'expo',
            'react',
            'react-native',
            'expo-router',
            '@expo/vector-icons',
        ],
        devDependencies: ['typescript', '@types/react'],
    },
    tauri: {
        name: 'tauri',
        displayName: 'Tauri',
        defaultName: 'my-tauri-app',
        description: 'Desktop applications with Rust backend and web frontend',
        supportedFeatures: {
            database: false,
            auth: false,
            storage: false,
            deployment: true,
            packageManager: true,
        },
        supportedDatabases: ['none'],
        supportedOrms: [],
        supportedStorage: ['none'],
        versions: {
            '@tauri-apps/api': '^2.1.1',
            '@tauri-apps/plugin-shell': '^2.0.1',
            vite: '^6.0.0',
            react: '^18.3.0',
            'react-dom': '^18.3.0',
            typescript: '^5.6.0',
            '@types/react': '^18.3.0',
            '@types/react-dom': '^18.3.0',
            '@vitejs/plugin-react': '^4.3.0',
        },
        requiredDependencies: ['@tauri-apps/api', '@tauri-apps/plugin-shell', 'react', 'react-dom'],
        devDependencies: [
            'vite',
            '@vitejs/plugin-react',
            'typescript',
            '@types/react',
            '@types/react-dom',
        ],
    },
    flutter: {
        name: 'flutter',
        displayName: 'Flutter',
        defaultName: 'my_flutter_app',
        description: 'Cross-platform apps with Dart',
        supportedFeatures: {
            database: false,
            auth: false,
            storage: false,
            deployment: true,
            packageManager: false,
        },
        supportedDatabases: ['none'],
        supportedOrms: [],
        supportedStorage: ['none'],
        versions: {
            flutter: '>=3.24.0',
            dart: '>=3.5.0 <4.0.0',
        },
        requiredDependencies: [],
        devDependencies: [],
    },
};
