/**
 * Vercel Blob操作関連の型定義
 */

/**
 * Blobストア情報
 */
export type BlobStore = {
    /** ストアID */
    id: string;
    /** ストア名 */
    name: string;
    /** 作成日時 */
    createdAt: string;
    /** 最終更新日時 */
    updatedAt: string;
    /** リージョン */
    region?: string;
    /** ストアURL */
    url: string;
};

/**
 * Blobストア作成オプション
 */
export type CreateBlobStoreOptions = {
    /** ストア名 */
    name: string;
    /** 読み書きトークン */
    token?: string;
    /** リージョン */
    region?: string;
};

/**
 * Blobストア作成結果
 */
export type BlobStoreResult = {
    /** 作成されたストア情報 */
    store: BlobStore;
    /** 生成されたトークン */
    token: string;
    /** 成功フラグ */
    success: boolean;
};

/**
 * Blobストア一覧取得オプション
 */
export type ListBlobStoresOptions = {
    /** アクセストークン */
    token?: string;
    /** 取得制限数 */
    limit?: number;
};

/**
 * Blobトークン検証結果
 */
export type TokenValidationResult = {
    /** 有効性フラグ */
    valid: boolean;
    /** エラーメッセージ */
    error?: string;
};

/**
 * Blobトークン作成オプション
 */
export type CreateBlobTokenOptions = {
    /** ストアID */
    storeId: string;
    /** トークンスコープ */
    scope?: "read" | "write" | "read_write";
    /** トークンタイプ */
    tokenType?: "user" | "service";
    /** 有効期限（秒） */
    expiresIn?: number;
};

/**
 * Blobトークン作成結果
 */
export type BlobTokenResult = {
    /** 生成されたトークン */
    token: string;
    /** トークンID */
    tokenId: string;
    /** トークンスコープ */
    scope: string;
    /** 有効期限 */
    expiresAt?: string;
    /** 成功フラグ */
    success: boolean;
};

/**
 * Blob設定
 */
export type BlobConfiguration = {
    /** 設定モード */
    mode: "new" | "existing" | "none";
    /** Blob使用フラグ */
    enabled: boolean;
    /** アクセストークン */
    token?: string;
    /** ストアID */
    storeId?: string;
    /** ストア名 */
    storeName?: string;
    /** ストアURL */
    storeUrl?: string;
    /** 発行されたトークンのID */
    tokenId?: string;
    /** トークンの有効期限 */
    tokenExpiresAt?: string;
    /** トークンのスコープ（read/write権限） */
    tokenScope?: string;
    /** 自動生成されたトークンかどうか */
    isAutoGenerated?: boolean;
};

/**
 * Blobエラーコード
 */
export const BlobErrorCode = {
    INVALID_TOKEN: "INVALID_TOKEN",
    STORE_NOT_FOUND: "STORE_NOT_FOUND",
    STORE_CREATION_FAILED: "STORE_CREATION_FAILED",
    TOKEN_CREATION_FAILED: "TOKEN_CREATION_FAILED",
    CLI_NOT_AVAILABLE: "CLI_NOT_AVAILABLE",
    NETWORK_ERROR: "NETWORK_ERROR",
    API_ERROR: "API_ERROR",
    AUTH_FAILED: "AUTH_FAILED",
    RATE_LIMITED: "RATE_LIMITED",
    TIMEOUT: "TIMEOUT",
} as const;

export type BlobErrorCode = (typeof BlobErrorCode)[keyof typeof BlobErrorCode];

/**
 * Blob操作エラー
 */
export class BlobOperationError extends Error {
    code: BlobErrorCode;
    recoverable: boolean;

    constructor(message: string, code: BlobErrorCode, recoverable = true) {
        super(message);
        this.name = "BlobOperationError";
        this.code = code;
        this.recoverable = recoverable;
    }
}

// EOF
