name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Check types
        run: pnpm exec tsc --noEmit

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run functional tests
        run: pnpm run test:functional

      - name: Test CLI
        run: |
          node dist/cli.js --version
          node dist/cli.js --help
