name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run E2E tests nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - nextjs
          - comprehensive

jobs:
  e2e-tests:
    name: E2E Tests - ${{ matrix.framework }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          # Next.js tests only
          - framework: nextjs
            os: ubuntu-latest
            node: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build CLI
        run: pnpm run build

      # No framework-specific setup needed for Next.js Vitest tests

      # Run E2E tests using Vitest
      - name: Run Next.js E2E Tests
        run: pnpm run test:e2e
        env:
          CI: true

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-e2e-report-${{ matrix.framework }}-${{ matrix.os }}
          path: |
            coverage/
            test-results/
          retention-days: 7

  # Comprehensive test that runs all frameworks
  comprehensive-e2e:
    name: Comprehensive E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: github.event_name == 'schedule' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'comprehensive'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build CLI
        run: pnpm run build

      # No additional setup needed for Vitest E2E tests

      # Run comprehensive E2E tests
      - name: Run Comprehensive E2E Tests
        run: pnpm run test:e2e:comprehensive
        env:
          CI: true

      # Generate test report
      - name: Generate Test Report
        if: always()
        run: |
          echo "# E2E Test Report" > test-report.md
          echo "Date: $(date)" >> test-report.md
          echo "" >> test-report.md
          if [ -f test-results/junit.xml ]; then
            echo "## Test Results" >> test-report.md
            # Parse junit.xml for summary (simplified)
            echo "See artifacts for full report" >> test-report.md
          fi

      - name: Upload comprehensive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: comprehensive-e2e-results
          path: |
            playwright-report/
            test-results/
            test-report.md
          retention-days: 30

  # Quick smoke test for PRs
  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build CLI
        run: pnpm run build

      # Run quick Next.js E2E test as smoke test
      - name: Run Smoke Tests
        run: pnpm run test:e2e:nextjs
        env:
          CI: true

      - name: Upload smoke test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: |
            coverage/
            test-results/
          retention-days: 7