name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update lockfile
        run: pnpm install --lockfile-only

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: bump version to v${{ steps.version.outputs.version }}'
          title: 'chore: release v${{ steps.version.outputs.version }}'
          body: |
            ## 🚀 Release v${{ steps.version.outputs.version }}

            This PR bumps the version to v${{ steps.version.outputs.version }}.

            ### Type of change
            - Version bump: `${{ github.event.inputs.version }}`

            ### Checklist
            - [ ] Tests pass
            - [ ] Build succeeds
            - [ ] Ready to publish to npm

            ---
            *This PR was automatically created by the release workflow.*
          branch: release/v${{ steps.version.outputs.version }}
          base: main
          labels: |
            release
            automated