name: Scenario Tests

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'test/scenario/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches:
      - main
      - develop
  schedule:
    # Run scenario tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scenario-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]
        framework: [nextjs, expo, tauri, flutter]
        include:
          # Add specific combinations for extended testing
          - os: ubuntu-latest
            node-version: 22
            framework: nextjs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Flutter-specific setup
      - name: Setup Flutter
        if: matrix.framework == 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      # Rust setup for Tauri
      - name: Setup Rust
        if: matrix.framework == 'tauri'
        uses: dtolnay/rust-toolchain@stable

      # Linux dependencies for Tauri
      - name: Install Linux Dependencies
        if: runner.os == 'Linux' && matrix.framework == 'tauri'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Run scenario tests for ${{ matrix.framework }}
        env:
          FLUORITE_TEST_MODE: 'true'
          FLUORITE_CLOUD_MODE: 'mock'
          FLUORITE_AUTO_PROVISION: 'false'
          TEST_FRAMEWORK: ${{ matrix.framework }}
        run: |
          pnpm run test:scenario -- test/scenario/${{ matrix.framework }}

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.framework }}
          path: |
            .temp-*/**
            test-results/
          retention-days: 7